### ISSUE TITLE
OpenCLCapsViewer does not open on new NVIDIA driver

### ISSUE THREAD

**Issue by xddxd** [SaschaWillems/OpenCLCapsViewer#8]
**Describe the bug**
OpenCLCapsViewer does not open if NVIDIA 511.23 driver is installed

**Expected behavior**
It should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/1712979/149597099-7d24f088-57f8-4283-8aa2-0f0f40420652.png)

**Platform (please complete the following information):**
 - Device: AMD Radeon RX580, NVIDIA GeForce GTX 960
 - OS: Windows 11
 - Driver version: AMD 22.1.1, NVIDIA 511.23

**Comment by SaschaWillems** [comment]
Thanks for raising this issue. I can confirm that this doesn't work on that driver version. I'm not yet sure if it's an application error or a driver bug. Will take a look at it.

**Comment by Andreyogld3d** [comment]
@SaschaWillems I confirm a bug, nVidia GT 1030 with new 511.23 driver.

**Comment by ValZapod** [comment]
What a coincedence.

**Comment by 4ngry** [comment]
Can confirm, that this does not work for mine nvidias too.

I've made an experiment with 511.23 driver, and commented-out first querying info of 'cl_khr_external_memory' extension at platform level, then the same error appeared when querying info for 'cl_khr_external_semaphore' at platform level. Seems that driver incorrectly puts that two strings into list of supported extensions, and OpenCLCapsViewer believes, that if driver forms list of extension name strings that means that extension is supported.

So, proposal here is two-fold: 
1) if OpenCLCapsViewer is supposed to support 511.23 driver, then it needs to somehow mark that 'cl_khr_external_memory' and 'cl_khr_external_semaphore' extensions at platform level as unsupported, maybe just by post-processing the string list in case on nvidia platform and version 511.23 driver;
2) if solution 1) considered as bad, just mention somewhere, that 511.23 driver is unsupported, and OpenCLCapsViewer won't run on this.

I think that this bug is somehow stops the database to be filled quickly, since usually people living on the latest drivers, and in current situation - it just does not work for them at all.

**Comment by SaschaWillems** [comment]
Just be patient. I have informed NVIDIA of that problem and they are looking into it. I'd rather prefer a fixed driver than having to add a hack for a certain driver combination.

**Comment by 4ngry** [comment]
Ok, but reading official doc on 'cl_khr_external_memory' extension it states that it is 'Provisional'. For me that means that working on that, querying info etc may be a bit dangerous, there may not be proper support along vendors, bugs, etc.

So maybe just have some sort of 'brave mode' in Caps Viewer which will include querying all that bleeding-edge stuff, and by default that 'brave mode' is turned off, so Caps Viewer works without bugs for most of users?

**Comment by SaschaWillems** [comment]
> Ok, but reading official doc on 'cl_khr_external_memory' extension it states that it is 'Provisional'. For me that means that working on that, querying info etc may be a bit dangerous, there may not be proper support along vendors, bugs, etc.

No that's not the meaning of provisional in terms of Khronos standards. Provisional means that the spec hasn't been finalized and may change with future updates. But even provisional extensions are supposed to properly work.

> So maybe just have some sort of 'brave mode' in Caps Viewer which will include querying all that bleeding-edge stuff, and by default that 'brave mode' is turned off, so Caps Viewer works without bugs for most of users?

Not sure on this. The caps viewer and the database is pretty new, so some of these problems are to be expected. Maybe I'll get back to that idea sometime in the future.

**Comment by StefanG3D** [comment]
Works again with R515 Windows insider driver.

**Comment by SaschaWillems** [comment]
Thanks for letting me know. Just tested myself with 511.79 and it works as expected. Also noticed that the database didn't display the external memory and semaphore handles, so I fixed that too.
